comment "Exported from Arsenal by FullAffect";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "rhs_uniform_FROG01_wd";
_this addItemToUniform "ACE_MapTools";
for "_i" from 1 to 10 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 5 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_epinephrine";};
_this addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_EarPlugs";};
_this addItemToUniform "ACE_salineIV_500";
_this addVest "rhsusf_spc_squadleader";
_this addItemToVest "ACE_EntrenchingTool";
for "_i" from 1 to 5 do {_this addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {_this addItemToVest "ACE_fieldDressing";};
_this addItemToVest "ACE_morphine";
_this addItemToVest "ACE_adenosine";
for "_i" from 1 to 2 do {_this addItemToVest "rhs_mag_an_m8hc";};
_this addItemToVest "rhs_mag_m18_green";
_this addItemToVest "rhs_mag_m18_red";
_this addItemToVest "rhs_mag_m18_yellow";
for "_i" from 1 to 2 do {_this addItemToVest "rhs_mag_m67";};
_this addItemToVest "ACE_HandFlare_White";
_this addItemToVest "ACE_HandFlare_Red";
for "_i" from 1 to 3 do {_this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
_this addBackpack "rhsusf_assault_eagleaiii_coy";
for "_i" from 1 to 5 do {_this addItemToBackpack "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {_this addItemToBackpack "HandGrenade";};
_this addItemToBackpack "ACE_HandFlare_Red";
_this addHeadgear "rhsusf_mich_helmet_marpatwd_headset";

comment "Add weapons";
_this addWeapon "rhs_weap_m4a1_carryhandle";
_this addPrimaryWeaponItem "rhsusf_acc_anpeq15side_bk";
_this addPrimaryWeaponItem "rhsusf_acc_EOTECH";
_this addWeapon "ACE_Vector";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "tf_anprc152";
_this linkItem "ItemGPS";
_this linkItem "rhsusf_ANPVS_15";
